# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

executors:
  my-sfdx-machine:
    docker:
      - image: circleci/openjdk:14-jdk-buster-node-browsers
    environment:
      SFDX_AUTOUPDATE_DISABLE: 'true'

jobs:
  test-apex:
    executor: my-sfdx-machine
    steps:
      - checkout
      - run:
          name: Run Apex Tests
          command: node scripts/js/testscript.js

workflows:
  main:
    jobs:
      - test-apex


